### ISSUE TITLE
OS version checking 

### ISSUE THREAD

**Issue by vds** [florianutz/Debian9-CIS#3]
Is the following line supposed to stop the playbook if applied to something different than Debian stretch?

https://github.com/florianutz/Debian9-CIS/blob/master/tasks/main.yml#L8

I'm running the playbook against Debian 10, Buster, there are a few weird things that I still need to triage, but the playbook gets applied.

I run the task through the debug, that's what I get: 

```
ASK [Debian9-CIS : Check OS version and family] ***********************************************************************
task path: /home/debian/Debian9_CIS/Debian9-CIS/tasks/main.yml:3                                                       
ok: [localhost] => {
    "msg": "ansible_distribution = Debian, ansible_distribution_release = buster"                                      
}

```

Probably the code should look like:

```
- name: Check OS version and family
  fail:
      msg: "This role can only be run against Debian stretch. {{ ansible_distribution }} {{ ansible_distribution_release }} is not supported."
  when: (ansible_distribution != "Debian") or
        (ansible_distribution_release != "stretch")
  tags:
      - always
          

```
