### ISSUE TITLE
Add support for offline machines.

### ISSUE THREAD

**Issue by vds** [florianutz/Debian9-CIS#5]
I'd like to add support for offline machines, which are not uncommon in environments with high security requirements.
So far, I've found only one place that requires the machine to be online:
https://github.com/florianutz/Debian9-CIS/blob/master/tasks/prelim.yml#L28

Instead of just commenting that code out, below I propose a more explicit way.

Debian9-CIS/defaults/main.yml 
```
# Offline machine
debian9cis_offline: false

```

Debian9-CIS/tasks/prelim.yml
```
- name: "PRELIM | Run apt cache update"
  apt:
    update_cache: true
  changed_when: false
  when:
      - not debian9cis_offline
```
